=== winterfroststrom/highschool_java_projects/CardGame/src/cardgame/Player.dtd
<?xml version='1.0' encoding='UTF-8'?>

<!--
    TODO define vocabulary identification
    PUBLIC ID: -//vendor//vocabulary//EN
    SYSTEM ID: http://server/path/Player.dtd

-->

<!--
    An example how to use this DTD from your XML document:

    <?xml version="1.0"?>

    <!DOCTYPE player SYSTEM "Player.dtd">

    <player>
    ...
    </player>
-->

<!ELEMENT player (city,cardTotal,deck)>
    <!ELEMENT city (inner,outer,frontier)>
        <!ELEMENT inner (#PCDATA)>
        <!ELEMENT outer (#PCDATA)>
        <!ELEMENT frontier (#PCDATA)>
    <!ELEMENT cardTotal (#PCDATA)>
    <!ELEMENT deck (card*)>
        <!ELEMENT card (cardid,cardnum)>
            <!ELEMENT cardid (#PCDATA)>
            <!ELEMENT cardnum (#PCDATA)>

=== winterfroststrom/highschool_java_projects/CardGame/src/cardgame/C-01.xml
<?xml version="1.0" encoding="UTF-8"?>

<!--
    Document   : C-01.xml
    Created on : November 25, 2009, 4:24 PM
    Author     : Scalene
    Description:
        Purpose of the document follows.
-->

<!DOCTYPE player SYSTEM "Player.dtd">
<player>
    <city>
        <inner>1</inner>
        <outer>1</outer>
        <frontier>1</frontier>
    </city>
    <cardTotal>3</cardTotal>
    <deck>
        <card><cardid>1</cardid><cardnum>1</cardnum></card>
        <card><cardid>2</cardid><cardnum>1</cardnum></card>
        <card><cardid>3</cardid><cardnum>1</cardnum></card>
    </deck>
</player>
